### PR TITLE
Avoid loops in connection with the server

### PR DESCRIPTION
**Pull request by francescodelduchetto**
Client A connects to a server (running the `DynamicBridgeServer`) with a `SubscribeBridge`, then the server will create a `RosToMqttBridge` in order to provide that topic on mqtt. Client B connects with a `PublishBridge` on the same topic to the same server, then the server creates a  `MqttToRosBridge`. At this point on the server side there is a loop where the messages cycle indefinitely ROS -> MQTT -> ROS...

### CODE REVIEW

**Comment by marc-hanheide** [comment]
I think the is mostly a misunderstanding of the concept. If there’s a publishbridge created on client A, then client B shouldn’t do anything themselves. That’s the idea of the PublishBridge, that it creates the topic on the other side already. Otherwise you may want to us the Ros2Mqtt bridge, which doesn’t create the corresponding Mqtt2Ros automatically.

**Comment by francescodelduchetto** [comment]
But if you have 3 different hosts (1 server and 2 for client A and B) then client B has to initialize another SubscribeBridge in order to subscribe to the topic provided by client A, no? 

I thought about using directly MqttToRosBridge but it would need to manually specify the internal mqtt topic name (with the control_topic) in the yaml config file.

**Comment by marc-hanheide** [comment]
> But if you have 3 different hosts (1 server and 2 for client A and B) then client B has to initialize another SubscribeBridge in order to subscribe to the topic provided by client A, no?
> 
> I thought about using directly MqttToRosBridge but it would need to manually specify the internal mqtt topic name (with the control_topic) in the yaml config file.

I would expect that multi-node communication should work as expected, I.e., should there be multiple DynamicBridgeServers connected to the control topic, they should in response to a PublishBridge being started all create the local ROS publisher. Is this not working? Likewise a subscribebridge should  subscribe to the ros topic on all other connected DynamicBridges. But you are right that there is a problem in multi node setups... 

indeed multi-node use cases are somewhat “mentally demanding”, and I may not have thought this out completely

**Comment by marc-hanheide** [comment]
So, this PR makes absolute sense. I’m not sure it catches all cases in a multi node setup, but I agree it’s useful.

**Review by marc-hanheide — APPROVED** [review]

**Comment by marc-hanheide** [comment]
@francescodelduchetto, I have triggered a release of the new version as version 1.2.1

**Pull request merged**
