### PR TITLE
response code to message added

### PR DESCRIPTION
**Pull request by arsh09**
Added response code to message for easy debugging. 

The lookup is referenced from here: 
https://www.vtscada.com/help/Content/D_Tags/D_MQTT_ErrMsg.htm

### CODE REVIEW

**Comment by marc-hanheide** [comment]
Hi @arsh09 how confident are you that these codes are the ones used for the specific paho version? I tried to do something similar and found many mappings for different versions.

**Comment by arsh09** [comment]
Hi @marc-hanheide ,

With paho>=1.6, there seems to be a proper mapping with this file included in [paho-v1.6 and above](https://github.com/eclipse/paho.mqtt.python/blob/1.6.x/src/paho/mqtt/reasoncodes.py) which matches the MQTT v5.0.0 protocol reason codes [here](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901031). 

Unfortunately, the requirement.txt mentions paho>=1.2 in this [repository ](https://github.com/LCAS/mqtt_bridge/blob/melodic-devel/requirements.txt#L3) that is why I added MQTT v3.1.1 reason codes. If the requirement on paho is changed to v1.6 and above, there should be consistency in the reason codes and this PR won't be required.

**Comment by marc-hanheide** [comment]
So, have we considered upgrading to a more recent version? Would it work?

**Comment by marc-hanheide** [comment]
I fear this is not reporting the correct codes at the moment. We need to update paho at some point, but I think this leads us the wrong way.

**Pull request closed without merging**
