### PR TITLE
Implementing stable re-connection 

### PR DESCRIPTION
**Pull request by marc-hanheide**
This is WIP towards more resilience to disconnections. For the attention also of @gpdas

### CODE REVIEW

**Comment by marc-hanheide** [comment]
@gpdas and @Iranaphor, I changed a lot in the `mqtt_bridge` to handle unstable networks and reconnections. I'm not surprised it didn't work before, in particular because we assumed a so-called `clean session`, i.e., on reconnect none of the mqtt subscriptions were still in place. This is now different, and it works in all my test reliably (removed the network connection for a minute, changed the route while bridge was running). Can you please test/review this. I hope this is an end to the constant problems, and can now also handle switches between 4G and Wifi and any other temporary network disruption.

**Comment by gpdas** [comment]
@marc-hanheide , We tested this on robots at riseholme today. When we switched the network from wired to wifi and back to wired again. It took nearly a minute for VPN to reconnect through the new network connection. After that mqtt bridge reconnected after some seconds. All missed updates in the topic we were monitoring remotely (closest_node) were received after reconnecting to the broker.

**Comment by marc-hanheide** [comment]
> @marc-hanheide , We tested this on robots at riseholme today. When we switched the network from wired to wifi and back to wired again. It took nearly a minute for VPN to reconnect through the new network connection. After that mqtt bridge reconnected after some seconds. All missed updates in the topic we were monitoring remotely (closest_node) were received after reconnecting to the broker.

So, that's good, right? Still a bit strange it takes a minute to reconnect, but as far as MQTT is concerned this is fine, right? So, you approve?

**Comment by gpdas** [comment]
Yes, I approve this.
The only concern was the delay in VPN reconnection, and MQTT is working fine and QoS is also working fine with the missed updates of latched topics being published.

**Review by gpdas — APPROVED** [review]

**Comment by marc-hanheide** [comment]
> Yes, I approve this. The only concern was the delay in VPN reconnection, and MQTT is working fine and QoS is also working fine with the missed updates of latched topics being published.

The VPN reconnect being slow is separate matter. We should simply move to wireguard, really. It's already available to use, if you want to update the robots. We can use wireguard and openvpn together even, as they are routed between one another (may need some testing). 

I'll merge.

**Pull request merged**
